/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import * as THREE from "three";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/frames.glb");
  const jayAtGraduation = new THREE.TextureLoader().load(require("../../images/jayAtGraduation.jpeg"))
  const jayBarista = new THREE.TextureLoader().load(require("../../images/jayBarista.png"))
//   jayAtGraduation.matrixAutoUpdate = true

  return (
    <group {...props} dispose={null} position={[25, 0, -4]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube8_Frames_0.geometry}
            material={materials.Frames}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube8_Backside_0.geometry}
            material={materials.Backside}
          />
          <mesh
            // castShadow
            // receiveShadow
            // geometry={nodes.pCube8_Canvas_0.geometry}
            // material={materials.Canvas}
            position={[-25, 0, 1]}
          >
            <boxGeometry 
                args={[30, 30, 0.5]}
            />
            <meshBasicMaterial
                map={jayAtGraduation}
            />
          </mesh>
          {/* <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube9_Frames_0.geometry}
            material={materials.Frames}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube9_Backside_0.geometry}
            material={materials.Backside}
          />
          <mesh
            // castShadow
            // receiveShadow
            // geometry={nodes.pCube9_Canvas_0.geometry}
            // material={materials.Canvas}
            position={[25, 0, 1]}
          >
            <boxGeometry 
                args={[35, 6, 1]}
            />
            <meshBasicMaterial 
                map={jayBarista}
            />
          </mesh> */}
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/frames.glb");