/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Víctor Hernández (https://sketchfab.com/victorhugohc)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/bus-stop-1ff7401eb178451b94257d1f8f15fd62
title: Bus stop
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0.5]} scale={10} position={[0, -50, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Texture001} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Texture002} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Texture003} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Texture004} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Texture005} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['Material.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
