/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import * as THREE from "three";
import { useGLTF } from "@react-three/drei";

export function Frame(props) {
  const { nodes, materials } = useGLTF("/frames.glb");
  const jayAtGraduation = new THREE.TextureLoader().load(require("../../images/jayAtGraduation.jpeg"))

  return (
    <group {...props} dispose={null} position={[25, 0, -4]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube8_Frames_0.geometry}
            material={materials.Frames}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube8_Backside_0.geometry}
            material={materials.Backside}
          />
          <mesh
            position={[-25, 0, 1]}
          >
            <boxGeometry 
                args={[30, 30, 0.5]}
            />
            <meshBasicMaterial
                map={jayAtGraduation}
            />
          </mesh>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/frames.glb");